### ISSUE TITLE
Limitation information is mismatch between doc on Github and the old ones.

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/element-software-123#7]
The below documentation and the previous version have wrong information about the limitation of how many initiators can one access group have.

Below is wrong:
https://docs.netapp.com/sfe-120/index.jsp?topic=%2Fcom.netapp.doc.sfe-mg-vcp%2FGUID-2B864E0E-A665-4693-A78E-8128B4F6FBB3.html&cp=4_1_12_4
A maximum of 64 IQNs or WWPNs are allowed in an access group.

Below is right: 
https://docs.netapp.com/us-en/element-software-123/concepts/concept_solidfire_concepts_volume_access_groups.html
A maximum of 128 initiators per volume access group.

Please correct the wrong information of the above doc and the previous version's doc.

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang -Thank you for providing this feedback.
We will review and determine how best to address it.

**Comment by ntap-bmegan** [comment]
@netapp-pcarriga - Please update status or close if work is complete.

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang - I've got confirmation that "A maximum of 64 IQNs or WWPNs are allowed in an access group" is incorrect for Element 12.0 and earlier.
Currently the documentation form Element 12.0 and earlier is migrating from SDL Tridion Docs. After this migration completes, I'll update the documentation. Tracking in DOC-4291 so closing this ticket.
Thank you again for bringing this issue to our attention.

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang Thank you again for contacting NetApp. This topic refers to an earlier product release and has now been archived; we are not planning further updates. Apologies for providing incorrect information in my previous message. For the latest documentation on this product, see [the Element software deocumentation](https://docs.netapp.com/us-en/element-software/)
